on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-26.04]
        compiler: [gcc, clang]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config llvm-dev libzstd-dev cmake ninja-build
        if [ "${{ matrix.compiler }}" = "clang" ]; then
          sudo apt-get install -y clang
        fi
    - run: |
        opts=(
          -Bbuild
          -GNinja
          -DCMAKE_BUILD_TYPE=RelWithDebInfo
        )
        if [ "${{ matrix.compiler }}" = "clang" ]; then
          opts+=(
            -DCMAKE_C_COMPILER=clang
            -DCMAKE_CXX_COMPILER=clang++
          )
        fi
        cmake "${opts[@]}"
    - run: cmake --build build
    - working-directory: ./build
      run: ctest --output-on-failure
